# Generated by Django 4.1.3 on 2023-01-22 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_item_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='item',
            name='parent',
        ),
    ]
