# Generated by Django 4.2 on 2023-04-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_rename_till_no_merchant_account_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="account_type",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
