# Generated by Django 4.2 on 2023-04-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_merchant_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant",
            name="business_description",
            field=models.TextField(),
        ),
    ]
