# Generated by Django 4.2.3 on 2023-07-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_merchant_business_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Bank', 'Bank'), ('M-pesa Till', 'M-pesa Till'), ('M-pesa PayBill', 'M-pesa PayBill'), ('M-pesa Send Money', 'M-pesa Send Money')], max_length=100),
        ),
    ]
