# Generated by Django 4.2.3 on 2023-07-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_merchant_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
